---
- name: Install dependencies (Ubuntu)
  apt:
    name:
      - wget
      - unzip
    state: present
    update_cache: yes

- name: Download Terraform (Ubuntu)
  get_url:
    url: "{{ terraform_download_url }}/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /tmp/terraform.zip

- name: Install Terraform (Ubuntu)
  unarchive:
    src: /tmp/terraform.zip
    dest: "{{ terraform_install_dir }}"
    remote_src: yes
  notify: Terraform Installed